---
title: "Statistical analysis: sa621"
output: html_document
lang: russian
---


## Misc
* [Results](https://docs.google.com/spreadsheets/d/1T9MGrBXeyrGsI-NNjYYLkIw7k-h1XCG0qLsbCqQZsoc/pubhtml)
* [Video for last two lectures](https://www.youtube.com/playlist?list=PL1poMUvVlAqdRD5ww3w-VBNRCFwQMeQkJ)

## Bibliography

#### Probability
* Ash, Probability Tutoring Book
* Freund, Introduction to probability

#### Statistics
* **Harvey Motulsky, Intuitive Biostatistics**
* Gonick, Smith, A Cartoon Guide to Statistics
* Huff, How to Lie with Statistics

#### R
* [R cheatsheets](https://www.rstudio.com/resources/cheatsheets/) from Rstudio
* Kabacoff, R in action
* [Intro to probability and statistics using R](http://gis-lab.info/docs/books/kerns10_ipsur.pdf)

## Log and plan

#### Day 15, 10 march 2016 (plan)
* problem solving session (preparation for exam)

#### Day 14, 03 march 2016 (plan)
* tree 
* random forest for numeric and factor dependent variables

#### Day 13, 25 february 2016
* Scatter plot matrix
* Visualizing logit regression
* [script_13.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_13_scatter_matrix.R)


#### Day 12, 11 february 2016
* difference between linear regression and logit models
* visualizing regression, [script_12.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_12_visualise.R)

#### Day 11, 04 february 2016
* log properties
* logit model, [script_11.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_11_logit.R)
* marginal effects

#### [Hometask solution:](https://github.com/bdemeshev/sa621/raw/master/2015/ht_solution/hw.pdf) 
* thanks to Anna Tikhonova!

#### Day 10, 11 december 2015
* Age pyramid using `HH` package
* [script_10.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_10_age_pyramid_2.R)
* R-markdown: [age pyramid-2](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/age_pyramid.Rmd)
* R-markdown: [tiny presentation example](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/optional_part_solution.Rmd)


#### Day 9, 4 december 2015
* Age pyramid using `plotrix` package
* [script_09.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_09_age_pyramid.R)
* R-markdown: [age pyramid](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/super_research.Rmd)

#### Day 8, 19 november 2015
* Interpretation of coefficients in multivariate regression
* F-test for comparison of nested models
* Correlation
* [script_08.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_08_f_test.R)
* [Hometask is available!!!!](https://github.com/bdemeshev/sa621/raw/master/2015/home_task/sa621_ht_01.pdf)

#### Day 7, 12 november 2015
* Testing significance of coefficients: standard errors and p-values
* [script_07.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_07_linear_regression2.R)


#### Day 6, 05 november 2015
* Method of least squares
* Linear regression model
* [script_06.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_06_linear_regression.R)


#### Day 5, 19 october 2015
* Binomial distribution
* Hypothesis testing with binomial distribution
* Hypothesis testing with normal distribution
* [script_05.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_05_binomial_hyp_testing.R)

#### Day 4, 12 october 2015
* Normal distribution
* Density function, distribution function
* [script_04.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_04_histogram_normal_distribution.R)

#### Day 3, 05 october 2015
* Recap: expected value, $E(X)$, variance, $Var(X)$
* Estimators: sample mean, $\bar{X}$, for expected value $E(X)$; sample variance,
$\hat\sigma^2$ for $Var(X)$.
* histogram, scatter plot, violin plot in R
* Divide and conquer strategy, `dplyr` R-package, [script_03.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_03_dplyr_simple_graphs.R)



#### Day 2, 28 september 2015
* Random variables and events
* Expected value and probability
* Variance
* Uniform distribution
* Simulations in R: estimation of expected value and variance

#### Day 1, 21 september 2015
* Introduction to R:
  * vectors: [script_01.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_01_vector_sample.R)
  * data frames
  * loading data in `.csv` format, creating `.csv` files in Excel:  [data_sem_01.csv](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/data_sem_01.csv), [script_01b.R](https://github.com/bdemeshev/sa621/raw/master/2015/seminar_scripts/script_01b_data_frame_read.R)
* Homework: Install R, Rstudio, Latex. Installation instructions [по русски](https://github.com/bdemeshev/em301/wiki/R). For Windows users: If you have English login name, you will NOT encounter problems, just install [the R](https://cran.rstudio.com/), [Rstudio](https://www.rstudio.com/products/rstudio/download/) and [Texlive](https://www.tug.org/texlive/acquire-netinstall.html).


## License
All my materials for this course are published under [Creative Commons Attribution-NonCommercial-ShareAlike](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en)
